all:
	convert -delay 30 FilterUI-1~dark@2x.png  -delay 50 FilterUI-2~dark@2x.png  -loop 0 apng:FilterUI~dark@2x.png
	convert -delay 30 FilterUI-1~light@2x.png -delay 50 FilterUI-2~light@2x.png -loop 0 apng:FilterUI~light@2x.png
