all:
	convert -delay 25 Logo-1~dark@1x.png  -delay 50 Logo-2~dark@1x.png  -loop 0 apng:Logo~dark@1x.png
	convert -delay 25 Logo-1~dark@2x.png  -delay 50 Logo-2~dark@2x.png  -loop 0 apng:Logo~dark@2x.png
	convert -delay 25 Logo-1~light@1x.png -delay 50 Logo-2~light@1x.png -loop 0 apng:Logo~light@1x.png
	convert -delay 25 Logo-1~light@2x.png -delay 50 Logo-2~light@2x.png -loop 0 apng:Logo~light@2x.png
